### PR TITLE
Add ceph storage

### PR DESCRIPTION
**Pull request by bassamtabbara**
Add ceph to the base image. Ceph is huge and has many dependencies. The approach we took is to add only a few binaries that we need. These include ceph-mon, ceph-osd and ceph-mds. We also added a number of tools. The dependencies were kept mostly to what is already in CoreOS. The image size increased by about 35MB.

### CODE REVIEW

**Comment by travisn** [comment]
Is the 35MB increase on the compressed size?

**Comment by travisn** [comment]
Are the mon, osd, and mds unit files just for simple testing purposes? I believe we still expect them to be generated.

**Comment by travisn** [comment]
LGTM. Awesome to see it wasn't too painful

**Comment by bassamtabbara** [comment]
I think we should be able to use the unit files and customizing the config. Let's chat about that.

**Pull request merged**
