### PR TITLE
Merge coreos build 970

### PR DESCRIPTION
**Pull request by jbw976**

### CODE REVIEW

**Comment by jbw976** [comment]
Conflicts were resolved for coreos-base/coreos/coreos-0.0.1.ebuild

Biggest concern is their removal of virtual/udev, which we still depend on, right? I left that one in

ours: https://github.com/quantum/coreos-overlay/blob/master/coreos-base/coreos/coreos-0.0.1.ebuild

their recent changes of note: https://github.com/coreos/coreos-overlay/commits/master/coreos-base/coreos/coreos-0.0.1.ebuild

**Comment by bassamtabbara** [comment]
I wonder why udev was removed. It might have been an oversight. Worth asking @marineam

**Comment by marineam** [comment]
I dropped it from the list since it is covered by the systemd dep as well as deps of other things, no need to appear in high level list in that ebuild.

**Comment by bassamtabbara** [comment]
@marineam thank you!

**Comment by bassamtabbara** [comment]
LGTM

**Pull request merged**
